//! Combat-related components
//!
//! Defines the ECS components for combatants, stats, abilities, and effects.

use bevy::prelude::*;

/// Marker component for a combatant entity
#[derive(Component)]
pub struct Combatant {
    /// Display name of the combatant
    pub name: String,
    /// Team this combatant belongs to (0 or 1 for now)
    pub team: u8,
}

/// Health points component
#[derive(Component)]
pub struct Health {
    pub current: f32,
    pub maximum: f32,
}

impl Health {
    pub fn new(max: f32) -> Self {
        Self {
            current: max,
            maximum: max,
        }
    }

    pub fn percentage(&self) -> f32 {
        self.current / self.maximum
    }

    pub fn is_dead(&self) -> bool {
        self.current <= 0.0
    }

    pub fn is_low(&self) -> bool {
        self.percentage() < 0.25
    }
}

/// Resource type for combatants (mana, rage, energy, etc.)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResourceType {
    /// Mana - regenerates slowly, used by casters
    Mana,
    /// Rage - generated by dealing/taking damage, used by warriors
    Rage,
    /// Energy - regenerates quickly, used by rogues
    Energy,
    /// None - no resource (some basic combatants)
    None,
}

/// Resource component (mana, rage, energy)
#[derive(Component)]
pub struct Resource {
    pub resource_type: ResourceType,
    pub current: f32,
    pub maximum: f32,
}

impl Resource {
    pub fn mana(max: f32) -> Self {
        Self {
            resource_type: ResourceType::Mana,
            current: max,
            maximum: max,
        }
    }

    pub fn rage() -> Self {
        Self {
            resource_type: ResourceType::Rage,
            current: 0.0,
            maximum: 100.0,
        }
    }

    pub fn energy() -> Self {
        Self {
            resource_type: ResourceType::Energy,
            current: 100.0,
            maximum: 100.0,
        }
    }

    pub fn percentage(&self) -> f32 {
        if self.maximum == 0.0 {
            return 1.0;
        }
        self.current / self.maximum
    }
}

/// Combat statistics for a combatant
#[derive(Component)]
pub struct CombatStats {
    /// Base attack power
    pub attack_power: f32,
    /// Spell power (for magic abilities)
    pub spell_power: f32,
    /// Armor (reduces physical damage)
    pub armor: f32,
    /// Magic resistance (reduces magic damage)
    pub magic_resistance: f32,
    /// Attack speed (attacks per second)
    pub attack_speed: f32,
    /// Movement speed (units per second)
    pub movement_speed: f32,
}

impl Default for CombatStats {
    fn default() -> Self {
        Self {
            attack_power: 100.0,
            spell_power: 100.0,
            armor: 0.0,
            magic_resistance: 0.0,
            attack_speed: 1.0,
            movement_speed: 5.0,
        }
    }
}

/// An active aura (buff or debuff) on a combatant
#[derive(Component)]
pub struct Aura {
    /// Display name of the aura
    pub name: String,
    /// Entity that applied this aura (for tracking)
    pub source: Entity,
    /// Remaining duration in seconds (None = permanent)
    pub remaining_duration: Option<f32>,
    /// Whether this is a buff (beneficial) or debuff (harmful)
    pub is_buff: bool,
    /// Whether this is a crowd control effect
    pub is_crowd_control: bool,
}

/// Marker for entities under crowd control
#[derive(Component)]
pub struct CrowdControlled {
    /// Type of crowd control
    pub cc_type: CrowdControlType,
}

/// Types of crowd control effects
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CrowdControlType {
    /// Cannot move or act
    Stun,
    /// Forced to run away
    Fear,
    /// Asleep - breaks on damage
    Sleep,
    /// Frozen in place
    Freeze,
    /// Turned into a harmless creature
    Polymorph,
    /// Knocked down
    Knockdown,
}

/// Match statistics for a combatant
#[derive(Component, Default)]
pub struct MatchStats {
    pub damage_done: f32,
    pub damage_received: f32,
    pub healing_done: f32,
    pub healing_received: f32,
    pub killing_blows: u32,
    pub crowd_control_done_seconds: f32,
    pub crowd_control_received_seconds: f32,
}

